//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArduinoService.Resource.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống điều khiển.
        /// </summary>
        public static string _0001 {
            get {
                return ResourceManager.GetString("0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống theo dõi.
        /// </summary>
        public static string _0002 {
            get {
                return ResourceManager.GetString("0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khiển đèn.
        /// </summary>
        public static string _0003 {
            get {
                return ResourceManager.GetString("0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khiển động cơ nước.
        /// </summary>
        public static string _0004 {
            get {
                return ResourceManager.GetString("0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khiển động cơ gió.
        /// </summary>
        public static string _0005 {
            get {
                return ResourceManager.GetString("0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở.
        /// </summary>
        public static string _0006 {
            get {
                return ResourceManager.GetString("0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tắt.
        /// </summary>
        public static string _0007 {
            get {
                return ResourceManager.GetString("0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ : Tiếng Việt.
        /// </summary>
        public static string _0008 {
            get {
                return ResourceManager.GetString("0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string _0009 {
            get {
                return ResourceManager.GetString("0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string _0010 {
            get {
                return ResourceManager.GetString("0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo dõi nhiệt độ.
        /// </summary>
        public static string _0011 {
            get {
                return ResourceManager.GetString("0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo dõi độ ẩm không khí.
        /// </summary>
        public static string _0012 {
            get {
                return ResourceManager.GetString("0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiệt độ.
        /// </summary>
        public static string _0013 {
            get {
                return ResourceManager.GetString("0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ ẩm không khí.
        /// </summary>
        public static string _0014 {
            get {
                return ResourceManager.GetString("0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string _0015 {
            get {
                return ResourceManager.GetString("0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái : Mở.
        /// </summary>
        public static string _0016 {
            get {
                return ResourceManager.GetString("0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái : Tắt.
        /// </summary>
        public static string _0017 {
            get {
                return ResourceManager.GetString("0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo dõi độ ẩm đất.
        /// </summary>
        public static string _0018 {
            get {
                return ResourceManager.GetString("0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ ẩm đất.
        /// </summary>
        public static string _0019 {
            get {
                return ResourceManager.GetString("0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        public static string _0020 {
            get {
                return ResourceManager.GetString("0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử theo dõi.
        /// </summary>
        public static string _0021 {
            get {
                return ResourceManager.GetString("0021", resourceCulture);
            }
        }
    }
}
