//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_GROUP_PERMISSION
    {
        public string PERMISSION_ID { get; set; }
        public string USER_ID { get; set; }
        public Nullable<bool> READ { get; set; }
        public Nullable<bool> WRITE { get; set; }
        public Nullable<bool> DELETE { get; set; }
        public Nullable<bool> SETTING { get; set; }
    }
}
