//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_PACKED
    {
        public string PACKED_ID { get; set; }
        public string PACKED_NAME_VN { get; set; }
        public string PACKED_NAME_EN { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    }
}
