//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_SETTING_CONTROL
    {
        public long SETTING_CONTROL_ID { get; set; }
        public string DEVICE_ID { get; set; }
        public Nullable<System.TimeSpan> TIME_ON { get; set; }
        public Nullable<System.TimeSpan> TIME_OFF { get; set; }
    }
}
