//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_SETTING_SENSOR
    {
        public long SETTING_SENSOR_ID { get; set; }
        public string DEVICE_SENSOR_ID { get; set; }
        public string LIMIT_LOW { get; set; }
        public string LIMIT_HIGH { get; set; }
        public string LIST_CONTROL_ID_OPEN { get; set; }
    }
}
