//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_ARDUINO_TYPE_DETAIL
    {
        public long ARDUINO_TYPE_DETAIL_ID { get; set; }
        public int ARDUINO_TYPE_ID { get; set; }
        public string PIN { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
    }
}
