//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CODE
    {
        public string CODE_ID { get; set; }
        public string CODE_VALUE { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
