//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_DEVICE
    {
        public string DEVICE_ID { get; set; }
        public string TOKEN_KEY { get; set; }
        public string DEVICE_NAME_VN { get; set; }
        public string DEVICE_NAME_EN { get; set; }
        public Nullable<int> DEVICE_CATEGORY { get; set; }
        public Nullable<int> GROUP_SENSOR_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> UNIT { get; set; }
        public string PIN_ID { get; set; }
    }
}
