//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_GARDEN
    {
        public string GARDEN_ID { get; set; }
        public string TOKEN_KEY { get; set; }
        public string GARDEN_NAME_VN { get; set; }
        public string GARDEN_NAME_EN { get; set; }
        public string USER_ID { get; set; }
        public int ACTIVE { get; set; }
        public string IMAGE { get; set; }
        public int UNO_TYPE { get; set; }
        public int STATUS { get; set; }
        public System.DateTime START { get; set; }
        public Nullable<System.DateTime> END { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> ACREAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> IS_SHEDULE { get; set; }
        public Nullable<bool> IS_AUTO { get; set; }
    }
}
