//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_GROUP_SENSOR
    {
        public int GROUP_SENSOR_ID { get; set; }
        public string GROUP_SENSOR_NAME { get; set; }
        public string NOTE { get; set; }
    }
}
